settings:
  disabled_events: [event1, event2, event3]
  commit_msg: "٩(̾●̮̮̃̾•̃̾)۶🔥Updated README🔥٩(̾●̮̮̃̾•̃̾)۶"
  max_lines: 0
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-04:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
