settings:
  disabled_events: [event1, event2, event3]
  commit_msg: "🔥Updated README🔥"
  max_lines: 1
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-04:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
