settings:
  readme_file: "./README.md"

  date:
    timezone: "America/Barbados"
    text: '<p align="center">Readme last refresh: <b>{DATE} IST</b>'
    commit_msg: Ê•Ê˜Ì…ÍœÊ˜Ì…Ê” ðŸ”¥README UPDATEDðŸ”¥ Ê•Ê˜Ì…ÍœÊ˜Ì…Ê”
