name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches: [ main ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: trinib/metrics@latest
        with:
          committer_message: 📈Profile metrics updated📈
          token: ${{ secrets.METRICS_TOKEN }}
          user: trinib
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, comment, push, star
